apiVersion: v1
kind: Namespace
metadata:
  name: npm-log-collector3
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: npm-log-collector3
rules:
  - apiGroups: [""]
    resources:
      - pods
      - services
    verbs:
      - list
  - apiGroups: ["networking.k8s.io"]
    resources:
    - networkpolicies
    verbs:
    - list
---
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: npm-log-collector3
    namespace: npm-log-collector3
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: npm-log-collector3
  namespace: npm-log-collector3
subjects:
  - kind: ServiceAccount
    name: npm-log-collector3
    namespace: npm-log-collector3
roleRef:
  kind: ClusterRole
  name: npm-log-collector3
  apiGroup: rbac.authorization.k8s.io
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azurefile3
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
parameters:
  skuName: Standard_LRS
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefile3
  namespace: npm-log-collector3
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile3
  resources:
    requests:
      storage: 100Gi
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: azure-npm-logger
  namespace: npm-log-collector3
  labels:
    app: azure-npm-logger-logger
spec:
  selector:
    matchLabels:
      k8s-app: azure-npm-logger
  template:
    metadata:
      labels:
        k8s-app: azure-npm-logger
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      serviceAccountName: npm-log-collector3
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      nodeSelector:
        beta.kubernetes.io/os: linux
      containers:
        - name: azure-npm-logger
          image: aksdebug/npm-logger:v1.0.0
          imagePullPolicy: Always
          securityContext:
            privileged: true
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          volumeMounts:
          - name: xtables-lock
            mountPath: /run/xtables.lock
          - name: log
            mountPath: /var/log
          - name: socket-dir
            mountPath: /var/run
          - name: tmp
            mountPath: /tmp
          - name: logcollector
            mountPath: /mnt/npmlogs  
      hostNetwork: true
      volumes:
      - name: log
        hostPath:
          path: /var/log
          type: Directory
      - name: xtables-lock
        hostPath:
          path: /run/xtables.lock
          type: File
      - name: tmp
        hostPath:
          path: /tmp
          type: Directory
      - name: socket-dir
        emptyDir: {}
      - name: logcollector
        persistentVolumeClaim:
          claimName: "azurefile3"
